spring:
  application:
    name: student-mini-portal-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
myorigin: "https://student-info-mini-portal-frontend/student-info-mini-portal-frontend/"